apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: yeasy/simple-web
        ports:
        - containerPort: 80
